FROM node:current

# Create and define the node_modules's cache directory.
WORKDIR /cache

# install app dependencies
COPY package.json .
COPY package-lock.json .
RUN npm install --silent

WORKDIR /sam-explorer
ENV PATH /sam-explorer/node_modules/.bin:$PATH