services:
  frontend:
    build:
      context: ./frontend/source
      dockerfile: ../Dockerfile.develop
    restart: no
    volumes:
      - "./frontend/source:/repo"
    ports:
      - 3000:3000
    # command: >
    #   bash -c "cp -rfu /cache/node_modules/. /repo/node_modules/  
    #   && npm start"
    command: >
      bash -c "npm start"

  backend:
    image: backend-server
    build:
      context: ./backend/
      # dockerfile: ../Dockerfile
    restart: no
    volumes:
      - "./backend/source:/repo"
    ports:
      - 8888:8888
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: jupyter lab --allow-root --ip=0.0.0.0